# Generated by Django 3.2.4 on 2021-07-08 19:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 8, 19, 45, 48, 621770, tzinfo=utc)),
        ),
    ]
