# Generated by Django 3.2.4 on 2021-07-08 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='auhtor',
            new_name='author',
        ),
    ]
