# Generated by Django 3.2.4 on 2021-07-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_comment_parents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parents',
            new_name='parent',
        ),
    ]
