# Generated by Django 3.2.4 on 2021-08-01 19:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0012_notificaiton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaiton',
            new_name='Notification',
        ),
    ]
