# Generated by Django 3.2.4 on 2021-08-01 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_auto_20210802_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notificaiton_type',
            new_name='notificaiton_Type',
        ),
    ]
